name: adyen_flutter
description: A Plugin for the Client side encryption of the credit card information to supports the Adyen API Integration flow.
version: 0.0.4
author: Alexandre Roba <alexandre.roba@arobanet.be>
homepage: https://github.com/lab-box/adyen_flutter

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.pikaway.adyen_flutter
    pluginClass: AdyenFlutterPlugin
